"""add course_syllabi table

Revision ID: 46c01c006fa1
Revises: b8d89abee0ab
Create Date: 2026-08-24 19:41:57.992836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46c01c006fa1'
down_revision: Union[str, Sequence[str], None] = 'b8d89abee0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_syllabi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('office', sa.String(length=100), nullable=True),
    sa.Column('office_hours', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('teaching_mode', sa.String(length=255), nullable=True),
    sa.Column('evaluation_method', sa.Text(), nullable=True),
    sa.Column('prerequisites_text', sa.Text(), nullable=True),
    sa.Column('course_objectives', sa.Text(), nullable=True),
    sa.Column('course_overview', sa.Text(), nullable=True),
    sa.Column('textbooks', sa.Text(), nullable=True),
    sa.Column('core_competencies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('weekly_plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('source_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_syllabi_offering_id'), 'course_syllabi', ['offering_id'], unique=True)
    # 주의: autogenerate가 이 테이블과 무관한 'uq_graduation_requirements_scope'/
    # 'ix_rag_chunks_embedding' drop도 같이 냈다 — raw SQL로 만든 인덱스라 모델
    # 선언에 없어서 매번 벌어지는 알려진 오탐(CLAUDE.md 테스트/검증 절 "알려진 한계"
    # 참고). 이 마이그레이션과 무관하므로 지웠다.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_syllabi_offering_id'), table_name='course_syllabi')
    op.drop_table('course_syllabi')
    # ### end Alembic commands ###
