"""init

Revision ID: 9138e7c65da1
Revises: 
Create Date: 2026-07-01 20:02:26.490068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '9138e7c65da1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_url', name='uq_activity_source_url')
    )
    op.create_index(op.f('ix_activities_category'), 'activities', ['category'], unique=False)
    op.create_index(op.f('ix_activities_deadline'), 'activities', ['deadline'], unique=False)
    op.create_index('ix_activities_embedding', 'activities', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_activities_posted_date'), 'activities', ['posted_date'], unique=False)
    op.create_index(op.f('ix_activities_source'), 'activities', ['source'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('major', sa.String(length=200), nullable=True),
    sa.Column('default_category', sa.String(length=50), nullable=True),
    sa.Column('credits', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=False)
    op.create_table('requirement_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('major', sa.String(length=200), nullable=True),
    sa.Column('program_type', sa.String(length=20), nullable=True),
    sa.Column('curriculum_year', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('required_total_credits', sa.Integer(), nullable=True),
    sa.Column('rule_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_activity_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('career_weight', sa.Float(), nullable=True),
    sa.Column('recency_weight', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_id', name='uq_user_activity_rec')
    )
    op.create_index(op.f('ix_user_activity_recommendations_activity_id'), 'user_activity_recommendations', ['activity_id'], unique=False)
    op.create_index(op.f('ix_user_activity_recommendations_final_score'), 'user_activity_recommendations', ['final_score'], unique=False)
    op.create_index(op.f('ix_user_activity_recommendations_user_id'), 'user_activity_recommendations', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('career_goal', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=True)
    op.create_table('graduation_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audit_year', sa.String(length=10), nullable=True),
    sa.Column('audit_semester', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graduation_audits_user_id'), 'graduation_audits', ['user_id'], unique=False)
    op.create_table('portal_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portal', sa.String(length=50), nullable=False),
    sa.Column('login_id', sa.String(length=100), nullable=False),
    sa.Column('encrypted_password', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_credentials_user_id'), 'portal_credentials', ['user_id'], unique=True)
    op.create_table('student_course_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('raw_course_code', sa.String(length=50), nullable=True),
    sa.Column('raw_course_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('credits', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('grade_point', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_retake', sa.Boolean(), nullable=False),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_course_records_user_id'), 'student_course_records', ['user_id'], unique=False)
    op.create_table('user_academic_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requirement_set_id', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('major', sa.String(length=200), nullable=True),
    sa.Column('program_type', sa.String(length=20), nullable=False),
    sa.Column('curriculum_year', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_set_id'], ['requirement_sets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_academic_programs_user_id'), 'user_academic_programs', ['user_id'], unique=False)
    op.create_table('graduation_audit_program_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('user_academic_program_id', sa.Integer(), nullable=True),
    sa.Column('requirement_set_id', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['graduation_audits.id'], ),
    sa.ForeignKeyConstraint(['requirement_set_id'], ['requirement_sets.id'], ),
    sa.ForeignKeyConstraint(['user_academic_program_id'], ['user_academic_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graduation_audit_program_results_audit_id'), 'graduation_audit_program_results', ['audit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graduation_audit_program_results_audit_id'), table_name='graduation_audit_program_results')
    op.drop_table('graduation_audit_program_results')
    op.drop_index(op.f('ix_user_academic_programs_user_id'), table_name='user_academic_programs')
    op.drop_table('user_academic_programs')
    op.drop_index(op.f('ix_student_course_records_user_id'), table_name='student_course_records')
    op.drop_table('student_course_records')
    op.drop_index(op.f('ix_portal_credentials_user_id'), table_name='portal_credentials')
    op.drop_table('portal_credentials')
    op.drop_index(op.f('ix_graduation_audits_user_id'), table_name='graduation_audits')
    op.drop_table('graduation_audits')
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_activity_recommendations_user_id'), table_name='user_activity_recommendations')
    op.drop_index(op.f('ix_user_activity_recommendations_final_score'), table_name='user_activity_recommendations')
    op.drop_index(op.f('ix_user_activity_recommendations_activity_id'), table_name='user_activity_recommendations')
    op.drop_table('user_activity_recommendations')
    op.drop_table('requirement_sets')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_activities_source'), table_name='activities')
    op.drop_index(op.f('ix_activities_posted_date'), table_name='activities')
    op.drop_index('ix_activities_embedding', table_name='activities', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_activities_deadline'), table_name='activities')
    op.drop_index(op.f('ix_activities_category'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
